### ISSUE TITLE
Upgrade to Spring Security 4.0 / Java 7 / Servlet 3

### ISSUE THREAD

**Issue by leleuj** [pac4j/spring-security-pac4j#11]

**Comment by JacobASeverson** [comment]
Added PR https://github.com/pac4j/spring-security-pac4j/pull/17 that upgrades to Spring Security 4.0 and also updates the default filter url to `/client` as discussed in #13 . Seems the build is failing now on Travis build I don't think it has anything to do with the code, could you try a rebuild?

**Comment by leleuj** [comment]
The deployment to Sonatype has failed, it has nothing to do with the PR itself. Just pushed and merged: https://github.com/pac4j/spring-security-pac4j/pull/19
If you merged your PR with the master, it would rebuild without failing.

**Comment by JacobASeverson** [comment]
Just pushed up the rest of the upgrades that we talked about and looks like the build is solid again, thanks!

**Comment by leleuj** [comment]
Thanks. Reverted to servlet 3.0.1 instead of 3.1.0, to be on the latest version - 1 (like Java 7) to have a broader audience.

**Comment by leleuj** [comment]
I will re-test everything manually and cut the release (v1.3.0) if everything is ok.

**Comment by JacobASeverson** [comment]
Yeah that's a good call, thanks!
