### ISSUE TITLE
Add unit testing suite to the project

### ISSUE THREAD

**Issue by JacobASeverson** [pac4j/spring-security-pac4j#18]
I've done several custom Spring Security implementations and it can be easy to introduce subtle bugs once you start adding/subtracting features. My vote is for Spock, but whatever works :-)

**Comment by leleuj** [comment]
Owing to time constraints, I haven't spent time adding tests for pac4j implementations: most of the tests I'm doing are manual ones on the demo: https://github.com/pac4j/spring-security-pac4j-demo.

It's of course a good idea. I don't have any strong preference regarding the tests framework. Let's try Spok: start small and we'll see where we're going.
