### ISSUE TITLE
PAC4J exceptions doesn't trigger spring security mechanism

### ISSUE THREAD

**Issue by chameleooo** [pac4j/spring-security-pac4j#20]
Hello,

I have a problem using your lib. In the `ClientAuthenticationFilter`, `client.getCredentials(context)` throws pac4j exceptions and spring security's cannot handle them properly.

The exceptions have to be AuthenticationException in order to be catch in the `AbstractAuthenticationProcessingFilter`.

**Comment by leleuj** [comment]
Yes, it makes sense. I will review your pull request. Thanks for submitting it.

I plan to upgrade the spring-security-pac4j library very soon with the new pac4j v1.8 and cut a 1.4.0 release. This fix would got with it.

**Comment by leleuj** [comment]
BTW, how did you find ou this problem?

**Comment by chameleooo** [comment]
I'm using google oauth and a CredentialsException is thrown when the java session timeout on the account choice screen. This screen appear when you are logged to multiple google accounts. You can reproduce the problem by removing your cookies (JSESSIONID) before selecting an account. 

I didn't find any clean way to catch this exception so I start looking in spring-security authentication failure mechanisms.

**Comment by leleuj** [comment]
OK. I see.
