### ISSUE TITLE
Relative path for redirection

### ISSUE THREAD

**Issue by chameleooo** [pac4j/spring-security-pac4j#22]
Hello

I'm trying to configure my `Client` (Google2Client) with a relative callback URL because my application can be called with different URLs. I don't think this is possible for now. Am I right ? What can I do to bypass this problem ?

**Comment by leleuj** [comment]
A concept of contextual callback already exists, but it is not used in most clients like the google one. I plan to replace this limited implementation by a new feature in version 1.9. I guess the best option is currently to subclass the google client and compute the callback url your way.

**Comment by leleuj** [comment]
Closing. Will be addressed by: https://github.com/pac4j/pac4j/issues/198
