### ISSUE TITLE
Can you add the osgi manifest info like all the other pac4j modules?

### ISSUE THREAD

**Issue by garpinc** [pac4j/spring-security-pac4j#24]
The  other modules appear to have felix manifest stuff  in the pom

**Comment by leleuj** [comment]
Yes, will do that shortly.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/spring-security-pac4j/pull/25

**Comment by garpinc** [comment]
Perfect.. I assume that will get into the maven snapshot build tonight?

**Comment by leleuj** [comment]
Merging. It will be available in the SNAPSHOT after the build by Travis CI.
