### ISSUE TITLE
ClientAuthenticationToken doesn't erase credentials

### ISSUE THREAD

**Issue by davideanderson** [pac4j/spring-security-pac4j#3]
The implementation of ClientAuthenticationToken should override eraseCredentials() so that the credentials are correctly cleared out.  Currently, the AbstractAuthenticationToken.eraseCredentials() is called, which doesn't actually clear out any credentials because UsernamePasswordCredentials does not implement Spring's CredentialContainer.

Here is the implementation that AbstractAuthenticationToken uses:

    public void eraseCredentials() {
        eraseSecret(getCredentials());
        eraseSecret(getPrincipal());
        eraseSecret(details);
    }

    private void eraseSecret(Object secret) {
        if (secret instanceof CredentialsContainer) {
            ((CredentialsContainer)secret).eraseCredentials();
        }
    }

As you can see, since none of the parts of ClientAuthenticationToken implement CredentialsContainer, the erasing of credentials never actually does anything.

a potential implementation could simply be:

    public void eraseCredentials() {
        this.credentials = null;
        super.eraseCredentials();
    }

Though you have declared credentials to be final, so that would need to change, or some other mechanism would have to clear out the credentials.

**Comment by leleuj** [comment]
Any update on this?

**Comment by davideanderson** [comment]
Unfortunately, No progress.  However, this did actually cross my mind this weekend.  I'll see if I can put something together in the next couple of weeks.

**Comment by leleuj** [comment]
OK. Just let me know. I plan to do some work on the library in the next few weeks: upgrade to Spring Security 4, upgrade to pac4j v1.8...

**Comment by JacobASeverson** [comment]
Since the credentials can't depend on Spring Security, maybe the least hack way to do this is by adding a new implementation of `AuthenticationManager` that is more pac4j specific? It will add another piece to configure for users wanting that functionality, but it seems like that type of logic should stay in the `AuthenticationManager` type. If agreed I could have a PR ready this evening.

**Comment by JacobASeverson** [comment]
This PR gives us a way to do this. It provides an `AuthenticationManager` implementation that knows how to deal with `ClientAuthenticationToken`s. Using it requires the user to wire this new class into the client filter but that is a minimal task. I tested it with the spring-security-pac4j demo and it is good to go. https://github.com/pac4j/spring-security-pac4j/pull/13

**Comment by davideanderson** [comment]
The discussion at #13 covers what I was planning to do via PR.

**Comment by leleuj** [comment]
For spring-security-pac4j v1.3.0, in the `ClientAuthenticationToken`, remove the `final`  keyword for `credentials` and `userProfile` and make them `null` in an overrided `eraseCredentials` method.

For spring-security-pac4j v1.4.0, first add the "cleaning" capability in pac4j v1.8 (https://github.com/pac4j/pac4j/issues/250) and then use this feature to clean the credentials and user profile

**Comment by JacobASeverson** [comment]
I can get a PR ready, I'm assuming we don't want to set user profile to null though? Unless I'm missing something the application won't have access to the profile information that they need anymore unless they build a new provider that stores it somewhere correct?

**Comment by leleuj** [comment]
You're right, the user profile must not be cleaned.

**Comment by leleuj** [comment]
Marked now as 1.4.0 to use the "cleanable" capability of the `Credentials` which will be available in pac4j v1.8 (https://github.com/pac4j/pac4j/issues/250)

**Comment by leleuj** [comment]
Done by PR: #23
