### ISSUE TITLE
Allow custom Pricipal or UserDetails 

### ISSUE THREAD

**Issue by niconavarrete** [pac4j/spring-security-pac4j#5]
Hi,
I'd like to add a custom UserDetails to authentication, I've done a custom AuthenticationUserDetailsService<ClientAuthenticationToken> for that, but only credentials gets populated. 

Nearly every thing is final so I must nearly copy/pasted Provider, i'd ratherr prefer being able to subclass and override some method, or that the UserDetails from the AuthenticationUserDetailsService get's poulated as the pricipal or as the Auth details ....

------------------------------
        final ClientAuthenticationToken result = new ClientAuthenticationToken(credentials, clientName, userProfile,  authorities);
        if (userDetails == null){
        	result.setDetails(authentication.getDetails());
        }else{
        	result.setDetails(userDetails);
        }

Thanks agains for this wonderfull library.
Nico

**Comment by leleuj** [comment]
OK. I think I get it now.

**Comment by leleuj** [comment]
The PR: https://github.com/pac4j/spring-security-pac4j/pull/6

**Comment by leleuj** [comment]
Merged.

**Comment by niconavarrete** [comment]
Thanks.
