### ISSUE TITLE
Use both direct and indirect Cas clients in same application

### ISSUE THREAD

**Issue by panzerj** [pac4j/spring-security-pac4j#55]
I´ve got a spring-boot application for which I want some URLs to use the directCasClient with proxyTickets. However some parts of the application require interactive login via the indirectCasClient and the cas server`s login page.

Both ways work separately but I cannot get them work together.
Is there a Way?

**Comment by leleuj** [comment]
Please use the pac4j mailing list for questions. Did you take a look at this demo: https://github.com/pac4j/spring-security-pac4j-boot-demo? It has both authentication mechanisms: direct and indirect clients...
