### ISSUE TITLE
Problem with creating parameters for steam openId login

### ISSUE THREAD

**Issue by hudi1** [pac4j/spring-security-pac4j#60]
I want to create SteamOidcClient. 
Typical login url for steam looks like:

`https://steamcommunity.com/openid/login?openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.realm=https%3A%2F%2Fwww.dotabuff.com%2F&openid.return_to=https%3A%2F%2Fwww.dotabuff.com%2Fsignin%2Fcallback
`

but this is impossible to achieve with current pac4j implementation. For example client_id is required but steam dont need it. Then redirect parameter is `openid.return_to` not` redirect_uri` which is constant for `pac4j`. I really dont know standart of openId but when I compare google with steam it is completely 2 different options how to use openId.

**Comment by leleuj** [comment]
Are you sure you're not mistaken between the OpenID and OpenID Connect protocols?
Please use the mailing list: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users for questions.
