### ISSUE TITLE
Reactive support for CAS authentication

### ISSUE THREAD

**Issue by thirunar** [pac4j/spring-security-pac4j#61]
Hello everyone,
I'm trying to integrate, CAS authentication with spring-boot reactive application. I don't find a way to add the `CallbackFilter` when I define the filter chain. This is what I have tried:

        CallbackFilter callbackFilter = new CallbackFilter(config);
        callbackFilter.setMultiProfile(true);

        return http
                .authorizeExchange()
                .pathMatchers("/admin/info").permitAll()
                .and()
                .addFilterAt(callbackFilter, SecurityWebFiltersOrder.AUTHENTICATION)
                .build();

`addFilterAt` expects the argument of type `WebFilter` but `CallbackFilter` is not that type. Is there a workaround for this? Does pac4j support Reactive implementation?

My research finding:

- java-cas-client doesn't have reactive support. refer [issue](https://github.com/apereo/java-cas-client/issues/247)
- Since, the cas client doesnt have the support so is the `spring-security`. Refer [issue](https://github.com/spring-projects/spring-security/issues/5887)

**Comment by leleuj** [comment]
Can you share a full demo on github so I can take a look? Maybe upgrade the https://github.com/pac4j/spring-security-pac4j-boot-demo in a reactive way on a specific branch...

**Comment by thirunar** [comment]
Thank you @leleuj. I have created a PR for your reference. Please let me know if you need further details.

**Comment by leleuj** [comment]
Thanks for sharing. It's clear now. We would need to implement the `WebFilter`,  but it's a reactive component while pac4j is blocking on its call. Changing the internals of pac4j to make it async is a long process which won't be completed until years.
Is there a way to easily wrap non-reactive component in a WebFilter?

**Comment by thirunar** [comment]
Actually, I'm looking for the same. I will share it here if I find something. Thank you for the information!!

**Comment by linjialong** [comment]
hi,@thirunar,have you foud the way to resolve this problem.if so,can you share that ?

**Comment by leleuj** [comment]
Closed due to inactivity.
