### ISSUE TITLE
Support SessionManagementFilter after CallbackFilter

### ISSUE THREAD

**Issue by lrozenblyum** [pac4j/spring-security-pac4j#62]
Hello team.
For our scenario of usage of pac4j + SAML 2.0 + Spring Security we need to use Spring Security 'maximumSessions' feature. 

```
http
				.antMatcher("/**") 
				.headers().frameOptions().disable().and()
				.addFilterBefore(callbackFilter, BasicAuthenticationFilter.class) // <-- pac4j
				.addFilterBefore(filter, BasicAuthenticationFilter.class) // <-- pac4j
				.csrf().disable()
				.sessionManagement()
					.sessionFixation().none()
					.sessionCreationPolicy(SessionCreationPolicy.ALWAYS)
					.maximumSessions( 1 ); // <-- here is the trick, configures SessionAuthenticationStrategy

```

At the moment pac4j + Spring Security doesn't support this feature (at least for indirect clients) because CallbackFilter doesn't call any further filters in the default Spring security filter chain.

This 'maximumSessions' feature is based on SessionManagementFilter from Spring Security which depends on the fact that it detects whether 'current' request is exactly the request where authentication has been performed and enforces additional restrictions on whether the user can further work with the system.

For indirect clients the 'callback' request is exactly the request where authentication has been performed. Due to the fact that 'CallbackFilter' doesn't execute further filters from the default chain, SessionManagementFilter has no chances to enforce the policy.

If I reverse SessionManagementFilter and CallbackFilter then again SessionManagementFilter doesn't know that the current request has been the 'authentication' request.

The workaround which I applied temporarily to my code (not elegant and maybe introducing some other problems not discovered yet):
1) provided my own CallbackFilter which always calls the next filter from the filter chain regardless the request is 'callback' or no
2) (!) provided my CallbackController to handle the 'callback' url to mitigate the problem that DispatcherServlet now receives the 'callback' request.

Official support of 'sessionManagement' for indirect clients in pac4j + spring security would be really helpful.

Based on mailing list discussion 
https://groups.google.com/forum/?fromgroups#!topic/pac4j-users/igzENWuLjpk

As Jérôme LELEU suggested pac4j might need to fall back to default ProfileManager and let SessionManagementFilter do its job.

---
Additional information:
When SessionManagementFilter rejects the authentication, the application is left in partially inconsistent state:
* from point of view of Idp the user is logged-in
* from spring security point of view the user is not logged in
* from pac4j point of view the user is logged in (due to presence of Pac4jConstants.USER_PROFILES attribute).

How to achieve consistency here it's an open question (from pac4j point of view it's easy to remove the USER_PROFILES attribute, however logging out from Idp looks like not an option here since it may harm other SP)

**Comment by leleuj** [comment]
Running the Spring Security filters is not easy.

@lrozenblyum did you find a better solution on your side?

**Comment by lrozenblyum** [comment]
@leleuj no unfortunately I haven't found a better solution

**Comment by leleuj** [comment]
OK. I'll try to revisit that after the v5 release.

**Comment by leleuj** [comment]
@lrozenblyum I think I have come up with a good solution. Can you try the version `5.1.0-SNAPSHOT`? You need to set the `applicationContext` on the `CallbackFilter` to make things work.

**Comment by lrozenblyum** [comment]
Thank you @leleuj! Hopefully I can check it later on. At the moment I don't have access to the project in which I connected pac4j to for SSO.

**Comment by leleuj** [comment]
No problem. Keep me posted.
